# -*- coding: utf-8 -*-
"""config.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iFQITaFMzogwpleX1aHaus7e30pAzWt1
"""

import os
from dotenv import load_dotenv

load_dotenv()

class Config:
  key = os.getenv("subscription_key")
  endpoint = os.getenv("endpoint")
  azure_storage_connection_string = os.getenv("azure_storage_connection_string")
  container_name = os.getenv("container_name")



