# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GwkQ-a39pI9iYECkv567xbpvGsbD--L_
"""

import streamlit as st
from services.blob_service import upload_blob
from services.credit_card_service import analyze_credit_card

def configure_interface():
  st.title("Upload de Arquivo DIO - Desafio 1 - Azure - FakeDocs")
  uploaded_file = st.file_uploader("Escolha um arquivo", type=["png", "jpeg", "jpg"])

  # Verifica se um arquivo foi enviado
  if uploaded_file is not None:
      st.success("Arquivo carregado com sucesso!")
      fileName = uploaded_file.name

      #Enviar para blob storage
      blob_url = upload_blob(uploaded_file, fileName)
      if blob_url:
        st.write(f"O arquivo '{file_name}' foi enviado ao Blob Storage com sucesso!")
        credit_card_info = analyze_credit_card(blob_url)
        show_image_and_validation(blob_url, credit_card_info)

      else:
        st.error(f"Erro ao enviar o arquivo: {e}")

def show_image_and_validation(blob_url, credit_card_info):
  st.image(blob_url, caption="Imagem carregada do Blob Storage", use_column_width=True)
  st.write("Resultado da Validação:")
  if credit_card_info and credit_card_info["card_name"]:
    # Exibe informações do cartão, se disponíveis
    st.markdown("<h1 style= 'color:green;>Cartão Válido</h1>", unsafe_allow_html=True)
    st.write(f"**Nome do Titular:** {credit_card_info['card_name']}")
    st.write(f"**Número do Cartão:** {credit_card_info.get('card_number', 'Não disponível')}")
    st.write(f"**Validade:** {credit_card_info.get('expiry_date', 'Não disponível')}")
    st.write(f"**Código de Segurança:** {credit_card_info.get('security_code', 'Não disponível')}")

  else:
    st.markdown("<h1 style= 'color:red;>Cartão Inválido</h1>", unsafe_allow_html=True)
    st.write("Cartão de crédito Inválido!")

if __name__ == "__main__":
  configure_interface()