# -*- coding: utf-8 -*-
"""blob_service.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13tg5KEF6XEU8kI21TVd-vdi1WIhyuafq
"""

import os
from azure.storage.blob import BlobServiceClient
import streamlit as st
from ultils.Config import Config

def upload_blob(file, file_name):
  try:
    connect_str = Config.AZURE_STORAGE_CONNECTION_STRING
    blob_service_client = BlobServiceClient.from_connection_string(connect_str)

    blob_client = blob_service_client.get_blob_client(container=Config.AZURE_STORAGE_CONTAINER_NAME, blob=file_name)
    blob_client.upload_blob(file, overwrite=True)
    return blob_client.url
  except Exception as ex:
    print(ex)



