# -*- coding: utf-8 -*-
"""credit_card_service.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nyllTPIEv3U2o9OuljYCdLzlQf6PJXve
"""

from azure.core.credentials import AzureKeyCredential
from azure.ai.documentintelligence import DocumentIntelligenceClient
from azure.ai.documentintelligence.models import AnalyzeDocumentRequest
from ultils.Config import Config

def analyze_credit_card(card_url):
   try:
    credential = AzureKeyCredential(Config.key)
    document_client = DocumentIntelligenceClient(endpoint=Config.endpoint, credential=credential)

    card_info = document_client.begin_analyze_document("prebuilt-creditCard",analyze_document_request(url_source=card_url))
    result = card_info.result()

    for document in result.documents:
      fields = document.get('fields', {})

      return {
          'card_name': fields.get('CardHolderName', {}).get('content'),
          'card_number': fields.get('CardNumber', {}).get('content'),
          'expiry_date': fields.get('ExpirationDate', {}).get('content'),
          'bank_name': fields.get('IssuingBank', {}).get('content')
      }


   except Exception as e:
    print(e)